version: '3.3'

services:
  postgres:
    image: postgres:14.5
    ports:
      - 5432:5432
    env_file:
      - django_core/django_core/.env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./dumps:/code/dumps

  backend:
    container_name: django_core
    build: ./django_core
    command: bash -c "pip install -r requirements.txt &&
      gunicorn -w 3 django_core.wsgi:application --bind 0.0.0.0:8000 --reload --log-level=info --access-logfile=- --error-logfile=-"
    ports:
      - 8000:8000
    volumes:
      - ./django_core:/django_core
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    expose:
      - 5672
    ports:
      - 15672:15672

  celery:
    container_name: celery
    build: ./django_core
    restart: always
    volumes:
      - ./django_core:/django_core
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    env_file:
      - django_core/django_core/.env

    depends_on:
      - rabbitmq
      - postgres
    command: celery -A django_core.celery:app worker -B -l DEBUG -c 3

    privileged: true


